// <auto-generated />
using System;
using IdleGuild.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdleGuild.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260704161148_AddIdleRewardClaims")]
    partial class AddIdleRewardClaims
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdleGuild.Domain.GameStates.PlayerGameState", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("Gold")
                        .HasColumnType("bigint")
                        .HasColumnName("gold");

                    b.Property<int>("HeroLevel")
                        .HasColumnType("integer")
                        .HasColumnName("hero_level");

                    b.Property<int>("HighestStage")
                        .HasColumnType("integer")
                        .HasColumnName("highest_stage");

                    b.Property<DateTimeOffset>("LastIdleRewardClaimedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_idle_reward_claimed_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("PlayerId")
                        .HasName("pk_player_game_states");

                    b.ToTable("player_game_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_game_states_gold_non_negative", "gold >= 0");

                            t.HasCheckConstraint("ck_player_game_states_hero_level_positive", "hero_level >= 1");

                            t.HasCheckConstraint("ck_player_game_states_highest_stage_positive", "highest_stage >= 1");
                        });
                });

            modelBuilder.Entity("IdleGuild.Domain.Rewards.IdleRewardClaimReceipt", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("AccumulatedSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("accumulated_seconds");

                    b.Property<DateTimeOffset>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at_utc");

                    b.Property<long>("GoldAwarded")
                        .HasColumnType("bigint")
                        .HasColumnName("gold_awarded");

                    b.Property<long>("GoldBalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("gold_balance_after");

                    b.HasKey("PlayerId", "IdempotencyKey");

                    b.ToTable("idle_reward_claim_receipts", null, t =>
                        {
                            t.HasCheckConstraint("ck_idle_reward_claim_receipts_accumulated_seconds", "accumulated_seconds >= 0 AND accumulated_seconds <= 28800");

                            t.HasCheckConstraint("ck_idle_reward_claim_receipts_gold_awarded", "gold_awarded >= 0");

                            t.HasCheckConstraint("ck_idle_reward_claim_receipts_gold_balance_after", "gold_balance_after >= 0");
                        });
                });

            modelBuilder.Entity("IdleGuild.Domain.Rewards.IdleRewardClaimReceipt", b =>
                {
                    b.HasOne("IdleGuild.Domain.GameStates.PlayerGameState", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
