// <auto-generated />
using System;
using IdleGuild.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdleGuild.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260710152200_OptimizeGoldLedgerAdminQuery")]
    partial class OptimizeGoldLedgerAdminQuery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdleGuild.Domain.Economy.GoldLedgerEntry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after");

                    b.Property<long>("BalanceBefore")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_before");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("Reason")
                        .HasColumnType("integer")
                        .HasColumnName("reason");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference_id");

                    b.HasKey("EntryId")
                        .HasName("pk_gold_ledger_entries");

                    b.HasIndex("PlayerId", "OccurredAtUtc", "EntryId")
                        .HasDatabaseName("ix_gold_ledger_entries_player_occurred_at_entry");

                    b.HasIndex("PlayerId", "Reason", "ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ux_gold_ledger_entries_player_reason_reference");

                    b.ToTable("gold_ledger_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_gold_ledger_entries_amount_non_zero", "amount <> 0");

                            t.HasCheckConstraint("ck_gold_ledger_entries_balance_equation", "balance_after = balance_before + amount");

                            t.HasCheckConstraint("ck_gold_ledger_entries_balances", "balance_before >= 0 AND balance_after >= 0");

                            t.HasCheckConstraint("ck_gold_ledger_entries_reason", "reason >= 1 AND reason <= 3");
                        });
                });

            modelBuilder.Entity("IdleGuild.Domain.GameStates.PlayerGameState", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("Gold")
                        .HasColumnType("bigint")
                        .HasColumnName("gold");

                    b.Property<int>("HeroLevel")
                        .HasColumnType("integer")
                        .HasColumnName("hero_level");

                    b.Property<int>("HighestStage")
                        .HasColumnType("integer")
                        .HasColumnName("highest_stage");

                    b.Property<int>("IdleRewardRemainderHundredths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("idle_reward_remainder_hundredths");

                    b.Property<DateTimeOffset>("LastIdleRewardClaimedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_idle_reward_claimed_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("PlayerId")
                        .HasName("pk_player_game_states");

                    b.ToTable("player_game_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_player_game_states_gold_non_negative", "gold >= 0");

                            t.HasCheckConstraint("ck_player_game_states_hero_level_positive", "hero_level >= 1");

                            t.HasCheckConstraint("ck_player_game_states_highest_stage_positive", "highest_stage >= 1 AND highest_stage <= 32");

                            t.HasCheckConstraint("ck_player_game_states_idle_reward_remainder", "idle_reward_remainder_hundredths >= 0 AND idle_reward_remainder_hundredths < 100");
                        });
                });

            modelBuilder.Entity("IdleGuild.Domain.Heroes.HeroUpgradeReceipt", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<long>("GoldBalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("gold_balance_after");

                    b.Property<long>("GoldCost")
                        .HasColumnType("bigint")
                        .HasColumnName("gold_cost");

                    b.Property<int>("HeroLevelAfter")
                        .HasColumnType("integer")
                        .HasColumnName("hero_level_after");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<int>("PreviousLevel")
                        .HasColumnType("integer")
                        .HasColumnName("previous_level");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.HasKey("PlayerId", "IdempotencyKey")
                        .HasName("pk_hero_upgrade_receipts");

                    b.ToTable("hero_upgrade_receipts", null, t =>
                        {
                            t.HasCheckConstraint("ck_hero_upgrade_receipts_consistency", "(outcome = 1 AND hero_level_after = previous_level + 1 AND gold_cost > 0) OR (outcome = 2 AND hero_level_after = previous_level AND gold_cost > gold_balance_after) OR (outcome = 3 AND previous_level = 297 AND hero_level_after = 297 AND gold_cost = 0)");

                            t.HasCheckConstraint("ck_hero_upgrade_receipts_gold", "gold_cost >= 0 AND gold_balance_after >= 0");

                            t.HasCheckConstraint("ck_hero_upgrade_receipts_levels", "previous_level >= 1 AND hero_level_after >= 1 AND hero_level_after <= 297");

                            t.HasCheckConstraint("ck_hero_upgrade_receipts_outcome", "outcome >= 1 AND outcome <= 3");
                        });
                });

            modelBuilder.Entity("IdleGuild.Domain.Rewards.IdleRewardClaimReceipt", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("AccumulatedSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("accumulated_seconds");

                    b.Property<DateTimeOffset>("ClaimedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at_utc");

                    b.Property<long>("GoldAwarded")
                        .HasColumnType("bigint")
                        .HasColumnName("gold_awarded");

                    b.Property<long>("GoldBalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("gold_balance_after");

                    b.Property<int>("ProductionPercent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("production_percent");

                    b.Property<int>("RemainderHundredths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("remainder_hundredths");

                    b.HasKey("PlayerId", "IdempotencyKey");

                    b.ToTable("idle_reward_claim_receipts", null, t =>
                        {
                            t.HasCheckConstraint("ck_idle_reward_claim_receipts_accumulated_seconds", "accumulated_seconds >= 0 AND accumulated_seconds <= 28800");

                            t.HasCheckConstraint("ck_idle_reward_claim_receipts_gold_awarded", "gold_awarded >= 0");

                            t.HasCheckConstraint("ck_idle_reward_claim_receipts_gold_balance_after", "gold_balance_after >= 0");

                            t.HasCheckConstraint("ck_idle_reward_claim_receipts_production_percent", "production_percent >= 100");

                            t.HasCheckConstraint("ck_idle_reward_claim_receipts_remainder", "remainder_hundredths >= 0 AND remainder_hundredths < 100");
                        });
                });

            modelBuilder.Entity("IdleGuild.Domain.Stages.StageChallengeReceipt", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<long>("CheckpointGoldAwarded")
                        .HasColumnType("bigint")
                        .HasColumnName("checkpoint_gold_awarded");

                    b.Property<long>("GoldBalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("gold_balance_after");

                    b.Property<int>("HeroPower")
                        .HasColumnType("integer")
                        .HasColumnName("hero_power");

                    b.Property<int>("HighestStageAfter")
                        .HasColumnType("integer")
                        .HasColumnName("highest_stage_after");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<int>("PreviousHighestStage")
                        .HasColumnType("integer")
                        .HasColumnName("previous_highest_stage");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<int>("ProductionBonusPercentAfter")
                        .HasColumnType("integer")
                        .HasColumnName("production_bonus_percent_after");

                    b.Property<int>("RequiredPower")
                        .HasColumnType("integer")
                        .HasColumnName("required_power");

                    b.Property<int>("TargetStage")
                        .HasColumnType("integer")
                        .HasColumnName("target_stage");

                    b.HasKey("PlayerId", "IdempotencyKey")
                        .HasName("pk_stage_challenge_receipts");

                    b.ToTable("stage_challenge_receipts", null, t =>
                        {
                            t.HasCheckConstraint("ck_stage_challenge_receipts_consistency", "(outcome = 1 AND target_stage = previous_highest_stage + 1 AND highest_stage_after = target_stage AND hero_power >= required_power) OR (outcome = 2 AND target_stage = previous_highest_stage + 1 AND highest_stage_after = previous_highest_stage AND hero_power < required_power AND checkpoint_gold_awarded = 0) OR (outcome = 3 AND target_stage <= previous_highest_stage AND highest_stage_after = previous_highest_stage AND checkpoint_gold_awarded = 0) OR (outcome = 4 AND target_stage > previous_highest_stage + 1 AND highest_stage_after = previous_highest_stage AND checkpoint_gold_awarded = 0)");

                            t.HasCheckConstraint("ck_stage_challenge_receipts_outcome", "outcome >= 1 AND outcome <= 4");

                            t.HasCheckConstraint("ck_stage_challenge_receipts_stage_range", "target_stage >= 1 AND target_stage <= 32 AND previous_highest_stage >= 1 AND previous_highest_stage <= 32 AND highest_stage_after >= 1 AND highest_stage_after <= 32");

                            t.HasCheckConstraint("ck_stage_challenge_receipts_values", "hero_power >= 10 AND required_power >= 10 AND production_bonus_percent_after >= 0 AND checkpoint_gold_awarded >= 0 AND gold_balance_after >= 0");
                        });
                });

            modelBuilder.Entity("IdleGuild.Domain.Economy.GoldLedgerEntry", b =>
                {
                    b.HasOne("IdleGuild.Domain.GameStates.PlayerGameState", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IdleGuild.Domain.Heroes.HeroUpgradeReceipt", b =>
                {
                    b.HasOne("IdleGuild.Domain.GameStates.PlayerGameState", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IdleGuild.Domain.Rewards.IdleRewardClaimReceipt", b =>
                {
                    b.HasOne("IdleGuild.Domain.GameStates.PlayerGameState", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IdleGuild.Domain.Stages.StageChallengeReceipt", b =>
                {
                    b.HasOne("IdleGuild.Domain.GameStates.PlayerGameState", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
